# Generated by Django 6.0.7 on 2026-08-13 12:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0007_invitation_revoked_by_and_last_sent_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceAuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('invitation_created', 'Invitation created'), ('invitation_accepted', 'Invitation accepted'), ('invitation_revoked', 'Invitation revoked'), ('invitation_declined', 'Invitation declined'), ('account_created_by_invitation', 'Account created by invitation'), ('member_joined', 'Member joined the organization'), ('member_provisioned', 'Member provisioned by an admin'), ('member_removed', 'Member removed'), ('member_role_changed', 'Member role changed'), ('member_suspended', 'Member suspended'), ('member_unsuspended', 'Member reinstated')], max_length=40)),
                ('actor_id', models.UUIDField(blank=True, null=True)),
                ('subject_id', models.UUIDField(blank=True, null=True)),
                ('subject_email', models.EmailField(blank=True, default='', max_length=254)),
                ('role', models.CharField(blank=True, default='', max_length=40)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'workspaces_audit_event',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['workspace', '-created_at'], name='workspaces__workspa_271e81_idx'), models.Index(fields=['subject_id'], name='workspaces__subject_37d112_idx')],
            },
        ),
    ]
