# Generated by Django 6.0.8 on 2026-08-14 10:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0010_invitation_one_live_per_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacemember',
            name='mfa_compliant',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='workspacemember',
            name='mfa_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='WorkspaceMFAEnforcement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('enforcing', 'Enforcing'), ('enforced', 'Enforced'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('checked_members', models.PositiveIntegerField(default=0)),
                ('noncompliant_members', models.PositiveIntegerField(default=0)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_enforcement', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'workspaces_mfa_enforcement',
                'indexes': [models.Index(fields=['state'], name='workspaces__state_2001cf_idx')],
            },
        ),
    ]
