# Generated by Django 6.0.8 on 2026-08-14 10:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0011_mfa_enforcement_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspaceinvitation',
            name='login_grant_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workspaceinvitation',
            name='login_grant_issued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='WorkspaceProvisionOperation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation_id', models.CharField(max_length=64)),
                ('username', models.CharField(max_length=255)),
                ('state', models.CharField(choices=[('started', 'Started'), ('charged', 'Charged'), ('account_created', 'Account created'), ('completed', 'Completed'), ('compensating', 'Compensating'), ('compensated', 'Compensated'), ('failed', 'Failed')], default='started', max_length=20)),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('credits', models.PositiveIntegerField(default=0)),
                ('attempt', models.PositiveIntegerField(default=1)),
                ('credits_to_refund', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provision_operations', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'workspaces_provision_operation',
                'indexes': [models.Index(fields=['state'], name='workspaces__state_0743be_idx')],
                'constraints': [models.UniqueConstraint(fields=('workspace', 'operation_id'), name='workspaces_provision_operation_unique')],
            },
        ),
    ]
